name: Test and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci

    - name: Test
      if: false
      run: npm run test:cov


  migration:
    runs-on: ubuntu-latest
    needs: coverage
    steps:
      - uses: actions/checkout@v3
      - name: Add production ENV variables for migration
        run: echo "${{secrets.ENV}}" > .env
      - name: Reinstall node_modules
        run: npm ci
      - name: Run migrations
        run: npm run migration:run



  deploy:
    needs: migration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm ci
          npm run build
          cp package*.json ./dist
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "chigozie-lendsqr-be-test"
          heroku_email: ${{secrets.DEPLOY_EMAIL}}
          appdir: dist
